---
title: "QRM_Project_Arima"
format: pdf
editor: visual
---

## Load Package

```{r message=FALSE}
#Load packages
library(tidyquant)
library(fpp3)
library(rugarch)
library(rmgarch)
library(forecast)
```

```{r}
# Import Data
sp_prices <- tq_get("^GSPC",
                 get = "stock.prices",
                 from = "2000-01-01",
                 to = "2021-12-31")
```

# Compute Returns

```{r}
#Compute the log returns
returns <- sp_prices |>
  arrange(date) |>
  mutate(ret = log(adjusted) - log(lag(adjusted))) |>
  select(symbol, date, ret) |>
  drop_na(ret)

data <- returns
```

# Specify sGarch model

```{r}
# Specify sGARCH model
spec <- ugarchspec(
    variance.model =
      list(model = "sGARCH",
           garchOrder = c(1,1)),
      mean.model =
      list(armaOrder = c(0,0),
      include.mean = TRUE),
    distribution.model = "sged"
)
```

# Fit Model

```{r}
# Fit to the data
data %>%
  pull(ret) -> y

sGARCH <- ugarchfit(spec = spec,
                     data = y,
                    solver = 'hybrid',
                    out.sample=1000)
sGARCH
```

# Residual Diagnostic

```{r}
# Standardized residuals
plot(sGARCH, which = 10)

# Standardaied Squared residuals
plot(sGARCH, which = 11)

```

# Rolling Forecast

```{r}
roll <- ugarchroll(spec = spec, 
                   data = data$ret,
                   n.ahead = 1,
                   refit.every = 100,
                   refit.window = "moving",
                   n.start = 1000,
                   solver = "hybrid",
                   window.size = 1000,
                   fit.control = list(),
                   calculate.VaR = TRUE, VaR.alpha = c(0.01, 0.025, 0.05),
                   keep.coef = TRUE)
show(roll)
```

# Error Metircs

```{r}
rugarch::report(roll, type = "fpm")
```

# Series standard error plot

```{r}
plot(roll, which = 3)
```
